name: Build documentation

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Requirements
      run: |
        pip install -r ./requirements.txt
    - name: Build docs
      run: |
        sphinx-build -b html . ./docs_build/
        cd docs_build
        touch .nojekyll
    - name: Deploy Test Build
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs_build
